name: Build documentation

on:
  push:
    paths:
    - 'docs/**'
    - 'README.md'
    - '.github/workflows/documentation.yml'

env:
  TITLE: Apos.Shapes
  DESCRIPTION: Shape rendering in MonoGame.
  BASE: Apos.Shapes
  REPO: https://github.com/Apostolique/Apos.Shapes/tree/main/
  URL: https://apostolique.github.io/Apos.Shapes/
  ANALYTICS: G-J3N95K2KKS

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name: Install apos-docs
      run: npm install apos-docs -g
    - name: Use apos-docs
      run: |
        apos-docs -t ${{ env.TITLE }} -d '${{ env.DESCRIPTION }}' -b ${{ env.BASE }} -r ${{ env.REPO }} -a ${{ env.ANALYTICS }} -u ${{ env.URL }}
        cd apos-docs
        npm i
        npm run build
        cd -
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apos-docs/_site
