name: Release to NuGet

on:
  push:
    tags:
    - 'v*'

env:
  SOURCE1: Source/Apos.Shapes.csproj
  SOURCE2: Source/Apos.Shapes.KNI.csproj

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'
    - name: Get version from tag
      run: |
        TAGVERSION=$(git describe --tags --abbrev=0)
        echo "TAGVERSION=${TAGVERSION:1}" >> $GITHUB_ENV
    - name: Pack with dotnet
      run: |
        dotnet pack ${{ env.SOURCE1 }} -c Release --include-source --include-symbols -o ./artifacts -p:Version=${{ env.TAGVERSION }}
        dotnet pack ${{ env.SOURCE2 }} -c Release --include-source --include-symbols -o ./artifacts -p:Version=${{ env.TAGVERSION }}
    - name: Push with dotnet
      run: dotnet nuget push ./artifacts/*.nupkg -k ${{ secrets.NUGETAPIKEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
